var data = [
  {
    id: 2398,
    label: "University of Arizona",
    size: 57803,
    university: "University of Arizona",
    percentage: 30,
    demand: 7,
    children: [
      {
        id: 0,
        label: "Col Arch Plan & Landscape Arch",
        university: "University of Arizona",
        percentage: 97,
        demand: 4,
        college: "Col Arch Plan & Landscape Arch",
        children: [
          {
            id: 1,
            university: "University of Arizona",
            college: "Col Arch Plan & Landscape Arch",
            department: "Col Arch Plan & Landscape Arch",
            label: "Col Arch Plan & Landscape Arch",
            percentage: 90,
            demand: 1,
            children: [
              {
                id: 2,
                label: "Heritage Conservation",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Col Arch Plan & Landscape Arch",
                percentage: 21,
                demand: 4,
                children: [
                  {
                    id: 3,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Col Arch Plan & Landscape Arch",
                    percentage: 24,
                    demand: 6,
                    children: [
                      {
                        id: 5,
                        label: "Main",
                        size: 1,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Col Arch Plan & Landscape Arch",
                        percentage: 87,
                        demand: 6,
                        children: [],
                      },
                    ],
                    size: 1,
                  },
                ],
                size: 1,
              },
            ],
            size: 1,
          },
          {
            id: 6,
            university: "University of Arizona",
            college: "Col Arch Plan & Landscape Arch",
            department: "Planning Degree Program",
            label: "Planning Degree Program",
            percentage: 45,
            demand: 5,
            children: [
              {
                id: 7,
                label: "Master of Science in Planning",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Planning Degree Program",
                percentage: 7,
                demand: 6,
                children: [
                  {
                    id: 8,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Planning Degree Program",
                    percentage: 60,
                    demand: 5,
                    children: [
                      {
                        id: 10,
                        label: "Main",
                        size: 27,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Planning Degree Program",
                        percentage: 21,
                        demand: 7,
                        children: [],
                      },
                    ],
                    size: 27,
                  },
                ],
                size: 27,
              },
              {
                id: 11,
                label: "Master of Science in Urban Planning",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Planning Degree Program",
                percentage: 4,
                demand: 1,
                children: [
                  {
                    id: 12,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Planning Degree Program",
                    percentage: 9,
                    demand: 2,
                    children: [
                      {
                        id: 14,
                        label: "Main",
                        size: 6,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Planning Degree Program",
                        percentage: 9,
                        demand: 3,
                        children: [],
                      },
                    ],
                    size: 6,
                  },
                ],
                size: 6,
              },
            ],
            size: 33,
          },
          {
            id: 15,
            university: "University of Arizona",
            college: "Col Arch Plan & Landscape Arch",
            department: "Sch of Landscape Architecture",
            label: "Sch of Landscape Architecture",
            percentage: 3,
            demand: 5,
            children: [
              {
                id: 16,
                label: "Real Estate Development Analysis",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 59,
                demand: 9,
                children: [
                  {
                    id: 17,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 25,
                    demand: 4,
                    children: [
                      {
                        id: 19,
                        label: "Main",
                        size: 1,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 56,
                        demand: 8,
                        children: [],
                      },
                    ],
                    size: 1,
                  },
                ],
                size: 1,
              },
              {
                id: 20,
                label: "Real Estate Development Finance",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 19,
                demand: 2,
                children: [
                  {
                    id: 21,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 6,
                    demand: 9,
                    children: [
                      {
                        id: 23,
                        label: "Online",
                        size: 1,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 60,
                        demand: 2,
                        children: [],
                      },
                    ],
                    size: 1,
                  },
                ],
                size: 1,
              },
              {
                id: 24,
                label: "Real Estate Development Practice",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 2,
                demand: 7,
                children: [
                  {
                    id: 25,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 34,
                    demand: 4,
                    children: [
                      {
                        id: 27,
                        label: "Main",
                        size: 1,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 28,
                        demand: 8,
                        children: [],
                      },
                    ],
                    size: 1,
                  },
                ],
                size: 1,
              },
              {
                id: 28,
                label: "Master in Real Estate Development",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 17,
                demand: 5,
                children: [
                  {
                    id: 29,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 97,
                    demand: 2,
                    children: [
                      {
                        id: 31,
                        label: "Main",
                        size: 18,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 37,
                        demand: 9,
                        children: [],
                      },
                      {
                        id: 33,
                        label: "Online",
                        size: 32,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 86,
                        demand: 6,
                        children: [],
                      },
                    ],
                    size: 50,
                  },
                ],
                size: 50,
              },
              {
                id: 34,
                label: "Master of Landscape Architecture",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 70,
                demand: 2,
                children: [
                  {
                    id: 35,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 1,
                    demand: 6,
                    children: [
                      {
                        id: 37,
                        label: "Main",
                        size: 35,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 8,
                        demand: 2,
                        children: [],
                      },
                    ],
                    size: 35,
                  },
                ],
                size: 35,
              },
              {
                id: 38,
                label: "Major in Sustainable Built Environments",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "Sch of Landscape Architecture",
                percentage: 97,
                demand: 7,
                children: [
                  {
                    id: 39,
                    label: "Undergraduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "Sch of Landscape Architecture",
                    percentage: 100,
                    demand: 4,
                    children: [
                      {
                        id: 41,
                        label: "Main",
                        size: 113,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 4,
                        demand: 5,
                        children: [],
                      },
                      {
                        id: 43,
                        label: "Online",
                        size: 44,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "Sch of Landscape Architecture",
                        percentage: 31,
                        demand: 2,
                        children: [],
                      },
                    ],
                    size: 157,
                  },
                ],
                size: 157,
              },
            ],
            size: 245,
          },
          {
            id: 44,
            university: "University of Arizona",
            college: "Col Arch Plan & Landscape Arch",
            department: "School of Architecture",
            label: "School of Architecture",
            percentage: 4,
            demand: 7,
            children: [
              {
                id: 45,
                label: "Master of Architecture",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "School of Architecture",
                percentage: 98,
                demand: 1,
                children: [
                  {
                    id: 46,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "School of Architecture",
                    percentage: 62,
                    demand: 7,
                    children: [
                      {
                        id: 48,
                        label: "Main",
                        size: 18,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "School of Architecture",
                        percentage: 0,
                        demand: 7,
                        children: [],
                      },
                    ],
                    size: 18,
                  },
                ],
                size: 18,
              },
              {
                id: 49,
                label: "Master of Science in Architecture",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "School of Architecture",
                percentage: 40,
                demand: 6,
                children: [
                  {
                    id: 50,
                    label: "Graduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "School of Architecture",
                    percentage: 80,
                    demand: 6,
                    children: [
                      {
                        id: 52,
                        label: "Main",
                        size: 20,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "School of Architecture",
                        percentage: 92,
                        demand: 5,
                        children: [],
                      },
                    ],
                    size: 20,
                  },
                ],
                size: 20,
              },
              {
                id: 53,
                label: "Major in Architecture",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "School of Architecture",
                percentage: 59,
                demand: 6,
                children: [
                  {
                    id: 54,
                    label: "Undergraduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "School of Architecture",
                    percentage: 45,
                    demand: 3,
                    children: [
                      {
                        id: 56,
                        label: "Main",
                        size: 256,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "School of Architecture",
                        percentage: 54,
                        demand: 6,
                        children: [],
                      },
                    ],
                    size: 256,
                  },
                ],
                size: 256,
              },
              {
                id: 57,
                label: "Pre-Architecture",
                university: "University of Arizona",
                college: "Col Arch Plan & Landscape Arch",
                department: "School of Architecture",
                percentage: 0,
                demand: 8,
                children: [
                  {
                    id: 58,
                    label: "Undergraduate",
                    university: "University of Arizona",
                    college: "Col Arch Plan & Landscape Arch",
                    department: "School of Architecture",
                    percentage: 87,
                    demand: 8,
                    children: [
                      {
                        id: 60,
                        label: "Main",
                        size: 183,
                        university: "University of Arizona",
                        college: "Col Arch Plan & Landscape Arch",
                        department: "School of Architecture",
                        percentage: 96,
                        demand: 10,
                        children: [],
                      },
                    ],
                    size: 183,
                  },
                ],
                size: 183,
              },
            ],
            size: 477,
          },
        ],
        size: 756,
      },
    ],
  },
];
